config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :articles

  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :title,  presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # deviseコントローラーにストロングパラメータを追加する
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    home_index_path
  end

  def after_sign_out_path_for(resource)
    user_session_path
  end

  def correct_user
    redirect_to new_user_session_path unless user_signed_in?
  end

  protected

  def configure_permitted_parameters
    # サインアップ時にnameとphone_numberのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :correct_user, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = '新規作成に成功しました'
      redirect_to articles_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = "更新しました。"
      redirect_to articles_url
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:success] = "#{@article.title}のデータを削除しました。"
    redirect_to articles_url
  end

  private

    def article_params
      params.require(:article).permit(:title, :content, :image, :remove_image)
    end

    def set_article
      @article = Article.find(params[:id])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 現在ログイン中のユーザーがいればtrue、そうでなければfalseを返す。
  def logged_in?
    !current_user.nil?
  end

end

app/views/articles/edit.html.erb
<% provide(:title, 'Edit') %>
<% provide(:class_text, 'article-edit') %>
<% provide(:button_text, '更新する') %>

<div class="container">
  <div class="col-md-10 col-md-offset-2">
    <h1><%= t('.edit') %></h1>
    <%= render 'shared/form' %>
  </div>
</div>

app/views/articles/index.html.erb
<% provide(:title, 'article_index') %>

<div class="container">
  <div class="col-md-10 col-md-offset-2">

  <h1><%= t('.index') %></h1>

  <div class="actions">
    <h3><%= link_to t('.create_article'), new_article_path, class: "btn btn-primary", id: "index-button" %></h3>
  </div>

  <table class="table table-condensed table-hover" id="table-articles">
    <thead>
      <tr>
        <th><%= t('.show_detail') %></th>
        <th><%= t('.title') %></th>
        <th><%= t('.content') %></th>
        <th><%= t('.image') %></th>
        <th><%= t('.edit_destroy') %></th>
      </tr>
    </thead>

    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to t('.detail'), article_path(article), class: "btn btn-primary" %></td>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= image_tag article.image.url if article.image? %></td>
        <td>
          <%= link_to t('.edit'), edit_article_path(article), class: "btn btn-success" %>
          <%= link_to t('.destroy'), article_path(article), method: :delete,
              data: { confirm: "削除してよろしいですか？" },
              class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>

  </div>
</div>

app/views/articles/new.html.erb
<% provide(:title, 'New') %>
<% provide(:class_text, 'article-new') %>
<% provide(:button_text, '新規作成') %>

<div class="container">
  <div class="col-md-10 col-md-offset-2">
    <h1><%= t('.new') %></h1>
    <%= render 'shared/form' %>
  </div>
</div>

app/views/articles/show.html.erb
<% provide(:title, 'article_show') %>

<div class="container">
  <div class="col-md-10 col-md-offset-2">

  <h1><%= t('.show') %></h1>

  <table class="table table-condensed table-hover" id="table-articles">
    <thead>
      <tr>
        <th><%= t('.title') %></th>
        <th><%= t('.content') %></th>
        <th><%= t('.image') %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @article.title %></td>
        <td><%= @article.content %></td>
        <td><%= image_tag @article.image.url if @article.image? %></td>
      </tr>
    </tbody>
  </table>

  <div class="actions">
    <%= link_to t('.edit'), edit_article_path(@article), class: "btn btn-success" %>
    <%= link_to t('.destroy'), article_path(@article), method: :delete,
          data: { confirm: "削除してよろしいですか？" },
          class: "btn btn-danger" %>
  </div>

  <div class="actions">
    <%= link_to t('.back-article-index'), articles_path, class: "btn btn-primary" %>
  </div>

  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-2">
    <h1>Dash Boards</h1>
    <% if logged_in? %>
      <h3><%= current_user.name %></h3>
      <div class="actions">
        <%= link_to t("users.shared.links.index_article"), articles_path, class: "btn btn-primary btn-dash" %><br />
        <%= link_to t("users.shared.links.edit_user"), edit_user_registration_path, class: "btn btn-primary btn-dash" %><br />
        <%= link_to t("users.shared.links.sign_out"), destroy_user_session_path, method: :delete, class: "btn btn-warning btn-dash" %>
      </div>
    <% else %>
      <div class="actions">
        <%= link_to t("users.shared.links.sign_in"), new_user_session_path, class: "btn btn-primary btn-dash" %><br />
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="home" class="big-bg">
      <div class="container">
        <% flash.each do |message_type, msg| %>
          <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
        <% end %>
      <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      入力した内容に<%= object.errors.count %>件のエラーがあります。
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= form_with(model: @article, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @article %>

  <%= f.label :title, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :content, class: "label-#{yield(:class_text)}" %>
  <%= f.text_area :content, class: "form-control" %>

  <%= f.label :image, class: "label-#{yield(:class_text)}" %><br />
  <%= f.file_field :image, class: "image" %><br />
  <h6><%= f.check_box :remove_image %>画像を削除する</h6>

  <div class="actions">
    <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %><br />
  </div>

  <%= link_to t('devise.shared.links.back'), :back, class: "back" %>

<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t(".sign_in"), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t(".sign_up"), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t(".forgot_your_password"), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('.didn_t_receive_unlock_instructions'), new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t('.sign_in_with_provider', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>